# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

aliases:
  - &docker
    - image: circleci/openjdk:8-jdk-node-browsers

  - &restore_yarn_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-node-{{ arch }}-{{ .Branch }}-
        - v1-node-{{ arch }}-

  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

jobs:
  test_source:
    docker: *docker

    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run: yarn test --maxWorkers=2

  build:
    docker: *docker
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
